### 

GET http://localhost:8000/api/products/

### 
POST http://localhost:8000/api/products/
Content-Type: application/json

{
"codigo": "PRB004",
"nombre": "Nueevo Producto", 
"descripcion": "Descripcion producto 5",
"precio": 7, 
"cantidad": 0,
"src": "https://i.pinimg.com/564x/86/0a/5d/860a5d0fa94212d0f5473de3a65ec912.jpg",
"estado_registro": false,
"estado": "INACTIVO"
}

### 

GET http://localhost:8000/api/products/6466849707c2fa7bf07f93e7

###
PUT http://localhost:8000/api/products/6466849707c2fa7bf07f93e7
Content-Type: application/json

{
 "estado_registro": true,
 "estado": "OUTOFSTOCK",
 "cantidad": 0
}

### 

GET http://localhost:8000/api/clients/

### 
POST http://localhost:8000/api/clients/
Content-Type: application/json

 {
"identificacion": "0956871256",
"nombre": "Usuario Prb",
"direccion": "Coop. Mouunt Via 1",
"telefono": "09632148",
"correo": "example@example.com",
"estado_registro": true
}

### 

GET http://localhost:8000/api/clients/6466d74e63f10256d25c7b1b

###
PUT http://localhost:8000/api/clients/6466d74e63f10256d25c7b1b
Content-Type: application/json

{
 "nombre": "Nombre Cliente Prb"
}