### 

GET http://localhost:8000/api/products/

### 
POST http://localhost:8000/api/products/
Content-Type: application/json

{
"codigo": "PRB004",
"nombre": "Nueevo Producto", 
"descripcion": "Descripcion producto 5",
"precio": 7, 
"cantidad": 0,
"src": "https://i.pinimg.com/564x/86/0a/5d/860a5d0fa94212d0f5473de3a65ec912.jpg",
"estado_registro": false,
"estado": "INACTIVO"
}

### 

GET http://localhost:8000/api/products/6466849707c2fa7bf07f93e7

###
PUT http://localhost:8000/api/products/6466849707c2fa7bf07f93e7
Content-Type: application/json

{
 "estado_registro": true,
 "estado": "OUTOFSTOCK",
 "cantidad": 0
}